name: pre-commit cache
description: Handle pre-commit cache
inputs:
  cache-dir-path:
    description: 'pre-commit cache directory path'
    required: false
    default: '~/.cache/pre-commit'
  config-path:
    description: 'pre-commit configuration filepath'
    required: false
    default: '.pre-commit-config.yaml'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found.'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Get Python version checksum
      id: py
      run: echo "checksum=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ inputs.cache-dir-path }}
        key: pre-commit|${{ steps.py.outputs.checksum }}|${{ hashFiles( inputs.config-path ) }}
        restore-keys: |
          pre-commit|${{ steps.py.outputs.checksum }}|
