name: 'Setup tox'
description: 'Install tox and restore cache'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found.'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Compile requirements
      run: python -m devtools --no-venv repo --no-sync --no-pre-commit-install
      shell: bash
    - name: Install dependencies
      run: pip install tox -c requirements-dev.txt
      shell: bash
    - name: Get python info
      id: python
      run: echo "checksum=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Restore tox environment
      id: cache
      uses: actions/cache@v3
      with:
        path: .tox
        key: tox|${{ runner.os }}|${{ github.workflow }}|${{ github.job }}|${{ steps.python.outputs.checksum }}|${{ hashFiles( 'tox.ini' , 'requirements*.txt') }}
