default_language_version:
  python: python3.10
minimum_pre_commit_version: '2.20.0'

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (project + examples)
        entry: tox run -q -e mypy -- src demo.py
        language: system
        files: ^(src/|demo\.py)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (tests)
        files: ^((src|tests)/)
        entry: tox run -q -e mypy -- tests
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (devtools)
        entry: tox run -q -e mypy -- devtools
        language: system
        files: ^(devtools/)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: isort
        exclude: ^(demo_resources|\.github)/
        args: ['--check-only', '--filter-files', '--settings-file', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: '22.12.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: black
        exclude: ^(demo_resources|\.github)/
        args: ['--check', '--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: flake8
        exclude: ^(demo_resources|\.github)/
        args: ['--config', '.flake8']
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
  - repo: https://github.com/aio-libs/sort-all
    rev: 'v1.2.0'
    hooks:
      - id: sort-all
        exclude: ^(demo_resources|\.github)/
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
