default_language_version:
  python: python3.10
minimum_pre_commit_version: '2.20.0'

ci:
  skip: [mypy]
  submodules: true

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (project + examples)
        entry: tox run -q -e mypy -- src demo.py
        language: system
        files: ^(src/|demo\.py)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (tests)
        files: ^((src|tests)/)
        entry: tox run -q -e mypy -- tests
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: isort
        exclude: ^(devtools|demo_resources|\.github)/
        args: ['--filter-files', '--settings-file', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: '23.1.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: black
        exclude: ^(devtools|demo_resources|\.github)/
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: flake8
        exclude: ^(devtools|demo_resources|\.github)/
        args: ['--config', '.flake8']
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
        additional_dependencies: [  # keep in sync with requirements/requirement-dev.in
          flake8-pyi>=22.11.0,
        ]
  - repo: https://github.com/aio-libs/sort-all
    rev: 'v1.2.0'
    hooks:
      - id: sort-all
        exclude: ^(devtools|demo_resources|\.github)/
        types: []  # Overwrite with empty in order to fallback to types_or
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
