default_language_version:
  python: python3.10
minimum_pre_commit_version: '2.20.0'
exclude: ^(demo_resources|\.github)/

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (project + examples)
        entry: tox -q -e mypy -- src demo.py
        language: system
        files: ^(src/|demo\.py)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (tests)
        files: ^((src|tests)/)
        entry: tox -q -e mypy -- tests
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy (devtools)
        entry: tox -q -e mypy -- devtools
        language: system
        files: ^(devtools/)
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: isort
        args: ['--check-only', '--filter-files', '--settings-file', 'pyproject.toml']
  - repo: https://github.com/psf/black
    rev: '22.12.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: black
        args: ['--check', '--config', 'pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: flake8
        args: ['--config', '.flake8']
