default_language_version:
    python: python3.10
minimum_pre_commit_version: '2.20.0'
exclude: ^(demo_resources|.github)/

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: tox -q -e mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: tox -q -e isort --
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: black
        name: black
        entry: tox -q -e black --
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: flake8
        name: flake8
        entry: tox -q -e flake8 --
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/jazzband/pip-tools
    rev: '6.10.0'  # Keep in sync with requirements-dev.txt
    hooks:
      - id: pip-compile
        name: pip-compile pyproject.toml
        args: [--no-allow-unsafe, --resolver=backtracking, --quiet, --output-file=requirements.txt, pyproject.toml]
        files: ^(pyproject\.toml|requirements\.txt)$
      - id: pip-compile
        name: pip-compile pyproject.toml (extra==dev)
        args: [--no-allow-unsafe, --resolver=backtracking, --quiet, --extra=dev, --output-file=requirements-dev.txt, pyproject.toml]
        files: ^(pyproject\.toml|requirements-dev\.txt)$
      - id: pip-compile
        name: pip-compile pyproject.toml (extra==test)
        args: [--no-allow-unsafe, --resolver=backtracking, --quiet, --extra=test, --output-file=requirements-test.txt, pyproject.toml]
        files: ^(pyproject\.toml|requirements-test\.txt)$
