name: Build and test

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.pyi'
      - '**/.gitignore'
      - '**/LICENSE'
      - '.bumpversion.cfg'
      - '.pre-commit-config.yaml'
      - '**.md'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths-ignore:
      - '**.pyi'
      - '**/.gitignore'
      - '**/LICENSE'
      - '.bumpversion.cfg'
      - '.pre-commit-config.yaml'
      - '**.md'
      - '.github/scripts/**'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      SOURCE_DATE_EPOCH:
        description: 'SOURCE_DATE_EPOCH value for reproducible builds'
        required: false
        type: string
      artifact-name:
        description: 'Artifact name'
        required: true
        default: 'pydiamond-dist'
        type: string
      run-tests:
        description: 'Run tests'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      SOURCE_DATE_EPOCH:
        description: 'SOURCE_DATE_EPOCH value for reproducible builds'
        required: false
        type: string
      artifact-name:
        description: 'Artifact name'
        required: true
        type: string
      run-tests:
        description: 'Run tests'
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    if: (github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')) && (!startsWith(github.event_name, 'workflow_') || inputs.run-tests != false)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        python_version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python_version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install dependencies
        run: pip install tox tox-gh-actions==2.11.0 -c requirements-dev.txt
      - name: Restore tox environment
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-
      - name: Launch tests
        run: tox

  build:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: ${{ inputs.SOURCE_DATE_EPOCH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install dependencies
        run: pip install tox -c requirements-dev.txt
      - name: Compute SOURCE_DATE_EPOCH from commit date
        if: env.SOURCE_DATE_EPOCH == ''
        run: |
          date=`git show ${{ github.sha }} --pretty="%ct" --no-patch`
          echo "Using SOURCE_DATE_EPOCH=${date}"
          echo "SOURCE_DATE_EPOCH=${date}" >> $GITHUB_ENV
      - name: Build packages
        run: tox -e build
      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name || 'pydiamond-dist' }}
          path: dist
