name: Build and test

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**/.gitignore'
      - '**/LICENSE'
      - '.bumpversion.cfg'
      - '**.md'
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/.gitignore'
      - '**/LICENSE'
      - '.bumpversion.cfg'
      - '**.md'
      - '.github/scripts/**'
      - '.github/workflows/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/build.yml'
      # re-include used workflow calls
      - '!.github/workflows/build-workflow-call.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        python_version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Launch tests
        run: tox

  dist:
    needs: test
    name: Build sdist/wheel
    uses: ./.github/workflows/build-workflow-call.yml
    with:
      artifact-name: pydiamond-dist
