name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.py'
      - 'tox.ini'
      - 'pyproject.toml'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths:
      - '**.py'
      - 'tox.ini'
      - 'pyproject.toml'
      # include current file
      - '.github/workflows/lint-format.yml'

jobs:
  check:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Launch tests
        run: tox -e flake8,black,isort

  # there is a bug with positional-only parameters on latest mypy version (0.971) on python 3.10.7
  # cf. https://github.com/python/mypy/issues/13627
  mypy:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Launch mypy
        run: tox -e mypy
