name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.py'
      - '**.pyi'
      - '.flake8'
      - 'tox.ini'
      - 'pyproject.toml'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths:
      - '**.py'
      - '**.pyi'
      - '.flake8'
      - 'tox.ini'
      - 'pyproject.toml'
      # include current file
      - '.github/workflows/lint-format.yml'

jobs:
  format:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Launch checks
        uses: ./.github/actions/run-tox
        with:
          tox-args: -e black,isort --parallel

  lint:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Launch checks
        uses: ./.github/actions/run-tox
        with:
          tox-args: -e mypy,flake8 --parallel
