name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/**.pyi?'
      - 'tests/**.pyi?'
      - 'devtools/**.pyi?'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'requirements/*.in'
      - '.github/actions/setup-tox/**'
      - '.github/actions/pre-commit/**'
      - '.github/workflows/lint-format.yml'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths:
      - 'src/**.pyi?'
      - 'tests/**.pyi?'
      - 'devtools/**.pyi?'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'requirements/*.in'
      - '.github/actions/setup-tox/**'
      - '.github/actions/pre-commit/**'
      - '.github/workflows/lint-format.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  format:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-20.04
    env:
      PRE_COMMIT_HOME: './.cache/pre-commit'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Restore pre-commit cache
        uses: ./.github/actions/pre-commit-cache
        with:
          cache-dir-path: ${{ env.PRE_COMMIT_HOME }}
      - name: Setup tox
        uses: ./.github/actions/setup-tox
      - name: Launch checks
        run: tox run-parallel --parallel-no-spinner -e black,isort,sort-all

  lint:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Setup tox
        uses: ./.github/actions/setup-tox
      - name: Launch checks
        run: tox run -e flake8

  type-checking:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Setup tox
        uses: ./.github/actions/setup-tox
      - name: Launch checks
        run: tox run -e mypy
