name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.py'
      - '**.pyi'
      - 'tox.ini'
      - 'pyproject.toml'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths:
      - '**.py'
      - '**.pyi'
      - 'tox.ini'
      - 'pyproject.toml'
      # include current file
      - '.github/workflows/lint-format.yml'

jobs:
  format:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install tox
      - name: Restore tox environment
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: ${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-
      - name: Launch checks
        run: tox -e black,isort --parallel
        env:
          TOX_PARALLEL_NO_SPINNER: '1'

  lint:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install tox
      - name: Restore tox environment
        uses: actions/cache@v3
        with:
          path: .tox
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-tox-${{ steps.setup-python.outputs.python-version }}-
      - name: Launch checks
        run: tox -e mypy,flake8 --parallel
        env:
          TOX_PARALLEL_NO_SPINNER: '1'
