name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.py'
      - 'tox.ini'
      - 'pyproject.toml'
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - '**.py'
      - 'tox.ini'
      - 'pyproject.toml'
      # include current file
      - '.github/workflows/lint-format.yml'

jobs:
  check:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Launch tests
        run: tox -e flake8,mypy,black,isort
