name: Lint/Format

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/**.pyi?'
      - 'tests/**.pyi?'
      - 'devtools/**.pyi?'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'requirements/*.in'
      - '.github/workflows/lint-format.yml'
  push:
    branches:
      - main
      - release/**
    tags-ignore:
      - '*'
    paths:
      - '**.pyi?'
      - '!.github/**.pyi?'
      - '.flake8'
      - '.pre-commit-config.yaml'
      - 'tox.ini'
      - 'pyproject.toml'
      - 'requirements/*.in'
      - '.github/workflows/lint-format.yml'

jobs:
  format:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Setup tox
        uses: ./.github/actions/setup-tox
      - name: Launch checks
        run: tox -e black,isort,sort-all --parallel
        env:
          TOX_PARALLEL_NO_SPINNER: '1'


  lint:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version:')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
      - name: Setup tox
        uses: ./.github/actions/setup-tox
      - name: Launch checks
        run: tox -e mypy,flake8 --parallel
        env:
          TOX_PARALLEL_NO_SPINNER: '1'
