name: Release a version

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build sdist/wheel
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: pydiamond-dist

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    name: Distribute packages
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v4
        with:
          name: pydiamond-dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Upload to Github Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            dist/*

  build-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete release
        run: gh release delete ${{ github.ref_name }} --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete tag
        run: git push --delete origin ${{ github.ref_name }}

  version-check:
    runs-on: ubuntu-latest
    outputs:
      minor_major_release: ${{ steps.check.outputs.minor_major_release }}

    steps:
      - name: Verify minor/major release
        id: check
        run: |
          import os
          import re
          version = "${{ github.ref_name }}"
          if re.match(r"^v\d+\.\d+\.0$", version):
              print("This is a minor/major release")
              with open(os.environ["GITHUB_OUTPUT"], "a") as fp:
                  print("minor_major_release=true", file=fp)
          else:
              print("This is not a minor/major release")
        shell: python

  make-release-branch:
    needs: [version-check, build]
    if: ${{ success() && needs.version-check.outputs.minor_major_release == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup 'github-actions' user
        uses: ./.github/actions/setup-github-actions-bot-user
      - name: Get release branch name
        run: echo "RELEASE_BRANCH_NAME=release/${GITHUB_REF_NAME%.0}.x" >> $GITHUB_ENV
      - name: Create release branch
        run: git checkout -b $RELEASE_BRANCH_NAME ${{ github.ref_name }}
      - name: Rewrite .bumpversion.cfg
        continue-on-error: true
        run: |
          python ./.github/scripts/rewrite_bumpversion_cfg.py ./.bumpversion.cfg
          git add .bumpversion.cfg
          git commit -m "[RELEASE] Updated .bumpversion.cfg"
      - name: Push created branch
        run: git push origin $RELEASE_BRANCH_NAME
